name: minimart
description: "A professional Flutter shopping application renamed to Mini Mart, built for the BnChina Academy."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  shortid: ^0.1.2
  shared_preferences: ^2.5.4
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/minimart.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/products/
    - assets/categories/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf